# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c199fb9e5b9e8ec2cdc045eb2b986feeaa7ed3e064b35abcfb6961882f7a1becfa351519938ec3d5e6d378036a60c37b9c2d06d85956f991e8308133117d98a

test:
  secret_key_base: d82d05cb6ae443cc78893aabef7cc4e4d7548083ab6ecaf49d538dae6dcdc1e2580bd6ce955c14ff92cfb84ab07daddd8ef093993edd145d84d1517d9ecb9f23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
